### ISSUE TITLE
its not working on ubuntu.

### ISSUE THREAD

**Issue by suvirbhargav** [uwdata/termite-data-server#10]

**Comment by jcchuang** [comment]
The data server is designed to provides the output of a topic model in JSON format, to help support the development of visualizations.  What you're seeing is the correct output.

You might want to check out the visualization project instead.
https://github.com/uwdata/termite-visualizations

**Comment by jcchuang** [comment]
Right now there is only one view, the term-topic matrix visualization.

**Comment by jcchuang** [comment]
What you're seeing IS the correct output.  What are you trying to do?  Let me know what bug you encounter (or analysis you're trying to do) and I can address it more specifically.  Otherwise I will close this ticket.

**Comment by jcchuang** [comment]
You're running the data server, and what you are seeing is THE CORRECT OUTPUT.  I don't understand what you're trying to accomplish...
