### ISSUE TITLE
still not running on Ubuntu.

### ISSUE THREAD

**Issue by suvirbhargav** [uwdata/termite-data-server#11]
I'm getting this nlp pipeline error with all the demos.
http://pastie.org/8979195
I've tried this with both openjdk 6 & 7. Any idea what could be wrong?
The error is gone after placing corenlp into tools directory. still can't see any termtopic visualization.

**Comment by jcchuang** [comment]
The demo script should now automatically download CoreNLP (which is used to split the sentences).  Please let me know if you encounter any further issues.
