### ISSUE TITLE
Mallet needs compilation

### ISSUE THREAD

**Issue by piskvorky** [uwdata/termite-data-server#8]
Downloading Termite and trying to run Mallet flows ends in `Exception in thread "main" java.lang.NoClassDefFoundError: cc/mallet/classify/tui/Text2Vectors`.

This is because Mallet expects compiled sources in its classpath, under `tools/mallet/class/`.

Maybe the Mallet makefile can be run automatically, in `setup_mallet.sh`? Or the compiled sources simply added to Termite repo?

Sorry if I missed something obvious, I don't know my way around Termite very well yet.

**Comment by jcchuang** [comment]
Hi @piskvorky , What are the set of commends that lead to this exception?

**Comment by piskvorky** [comment]
Just downloading Termite and running anything that uses Mallet (e.g. training on 20news). The compiled sources are missing from `tools/mallet/class`.

**Comment by jcchuang** [comment]
I added compiled *.class files into the repo, so that the repo can be "ready to run" as downloaded.  543fa7e6e8e90e201f4e6ed1f9696f9bdf17dfb3

There are still additional issues with how web2py is only setup for OS X at the moment. Will address that later...
